### ISSUE TITLE
Can you make the downloadable files available for the SecurityFest 2018? I do not have files for some of the questions in this CTF. Thanks

### ISSUE THREAD

**Issue by iamabhinavjain** [EmpireCTF/empirectf#1]

**Comment by Aurel300** [comment]
Hi,

Unfortunately I cannot fix this in general. For some CTFs I did not ask for permission to host the challenges. Sometimes the files are also quite large. I will try to do better in the future, but for now:

 - for SUCTF, the organisers actually released Docker images with all the challenges; I added the link to the top of the writeup
 - for SecurityFest CTF, I asked the admins and they are ok with me re-hosting the challenges, I added what I had as links in the **Files provided** sections of each challenge write-up

Hope that helps!
