### ISSUE TITLE
Google CTF Perfect Secrecy

### ISSUE THREAD

**Issue by Crypt-iQ** [EmpireCTF/empirectf#2]
Hi your solution to this was very smart, I enjoyed reading it.

There's a typo in the inequalities when you multiply the flag by 4. On the right hand side of the inequalities, it should be `2n` instead of `2x`, and `3n` instead of `3x`. Technically `<=` is not possible for any of the inequalities but that doesn't really matter.

**Comment by Aurel300** [comment]
@Crypt-iQ Thanks, I'm glad you enjoyed it!

And good catch. As for `≤`, I formulated it that way mostly to show exhaustiveness of the 4 cases.
