### ISSUE TITLE
empirectf/writeups/2018-09-14-CSAW-CTF-Quals/README.md KVM does not run

### ISSUE THREAD

**Issue by VictorAlonsoCM** [EmpireCTF/empirectf#3]
Hello, sorry for this issue but I have a problem with the kvm file.
The problem that I have is that I don't know how to run the file. When I  try to run it my Kali says that 
"open /dev/kvm: No such file or directory" and I don't know what to do, I followed many tutorials about how to run this kind of binaries but none of these work for me.
Can you help me please?

**Comment by Aurel300** [comment]
Hello,

sorry about that. It seems I forgot to upload the `kvm-challenge` file into the repo. I assume you cloned the writeups repo? In any case, the file is now at https://github.com/EmpireCTF/empirectf/blob/master/writeups/2018-09-14-CSAW-CTF-Quals/files/kvm-challenge.

If you already had the file but are actually having issues with opening it – it is an ELF binary file. To reverse it / look at the assembly contained within, you need to use a debugger / disassembler of some sort, i.e. IDA pro, radare2, gdb, Binary Ninja … As for running the file, you probably need some 64-bit Linux machine or VM.

Hope that helps!
